### ISSUE TITLE
User API

### ISSUE THREAD

**Issue by ivan-kralik** [vaclavHala/SpatialTracker#10]
Skúšali ste registráciu nového užívateľa? Ja keď zavolám:

`curl -v -H "Content-Type: application/json" -X POST -d '{"login":"test","password":"test","mail":"test@test.sk"}' http://localhost:8080/tracker/rest/user/`

dostanem odpoveď s kódom `400 - Bad request`

a do denníka sa zapíše správa `Failed to create user: []`.

V `http://localhost:3000/settings?tab=api` mám zaškrtnuté `Zapnúť webovú službu REST`.

Ďalej je zaujímavé, že keď prejdem na url `http://localhost:8080/tracker/rest/user/cokolvek`, kde miesto `cokolvek` napíšem čokoľvek okrem `me`, tak to mi to v prehliadači vyhodí dialóg HTTP autentizácie. Viete prosím, na základe čoho tento dialóg vyhadzuje? Nikde som nenašiel nastavenia autentizácie a riadenia prístupu v našej aplikácii. Zaujímavé je, že keď dám `http://localhost:8080/tracker/rest/user/me`, tak už to autentizáciu nevyhadzuje, ale rovno hodí stav 403.

**Comment by vaclavHala** [comment]
Jo registrace funguje ale musi se v tom redminu nastabit jeste ze se user muze sam zaregistrovat a neni treba overeni mailu (zalozka Authentication v settings - self registration:automatic). Udelam Docker image ktere uz budou mit vse pripravene, stejne te to treba na testovani. 

Browser ti vyhodi to okno vzdy kdyz je nekde treba Basic autentizace. To je vlastnost kazdeho browseru ze se tak chova.

Ten /me ti hodi 403 protoze se rovnou diva do hlavicek na Authorization (Basic) a nic nenajde.

**Comment by ivan-kralik** [comment]
Ďakujem za info, chápem, prečo mi prehliadač vyhodí dialógové okno autentizácie, len nechápem, prečo aplikácia posiela hlavičku "WWW-Authenticate" práve v prípade `/cokolvek`. Na základe akého nastavenia?

**Comment by vaclavHala** [comment]
No mne to nedela ale myslim ze je mozne ze to ten browser udela protoze dostane response code 401. Tu hlavicku WWW-Authenticate ti to poslalo? jestli ne tak to muze browser brat jako implicitni. Jestli ji to poslalo mozna to wildfly prida automaticky k responsu s kodem 401. 

Ale po mne to, jestli si spravne pamatuju, auth pri get user nikdy nechtelo (ani nema chtit, mam to rozbity :( )

**Comment by ivan-kralik** [comment]
Áno, pri navštívení url `http://localhost:8080/tracker/rest/user/test` to posiela hlavičku:

`WWW-Authenticate:Basic realm="Redmine API"`

Zaujímavý mi príde ten realm, vôbec netuším, odkiaľ sa to berie a na základe čoho táto hlavička posiela. Všimol som si, že keď pridám tento riadok:

`this.usersRedmine.detailsSomeUser("test");`

do metódy `detailsMe()`, začne už aj url `http://localhost:8080/tracker/rest/user/me` posielať túto hlavičku. Vyzerá to tak, že to má spoločné niečo s tým redmine.

**Comment by ivan-kralik** [comment]
Nenastavuje sa ešte niekde v redmine API kľúč? Všimol som si, že tá služba RedminUsersService závisí na nejakom parametre REDMINE_API_KEY, ktorý neviem, kde treba nastaviť (či v redmine alebo v našej aplikácii) a ako zistím jeho hodnotu

**Comment by vaclavHala** [comment]
Nastavuje se zatim natvrdaka, dostanes se k nemu pres mypage na adminovi (je to adminovo api klic, ne neco globalniho) na redmine homepage. Nakonec to bude tak udelany ze se nacte automaticky pri startu aplikace.

**Comment by ivan-kralik** [comment]
Pozeral som ten seminár zo security, čo sme mali, a vlastne hneď prvá úloha, čo sme tam robili, bola implementácia vlastného autentizačného mechanizmu (to jaas-example):

[(https://github.com/qa/pv243-a4m36jee-2016-security-seminar)]

Ja by som navrhoval urobiť autentizáciu a autorizáciu cez to Java EE Security a implementovať vlastný autentizačný mechanizmus využívajúci redmine. Keďže už viem, ako funguje redmine autentizácia, idem to skúsiť urobiť.

**Comment by ivan-kralik** [comment]
Urobil som `RedmineLoginModule`, ktorý využíva `RedmineUserService` na overenie používateľa. Keď je používateľ úspešne overený, pridá sa mu rola "user", ktorú je možné ďalej použiť v rámci Java EE Security. Je ale potrebné pridať pár riadkov do standalone.xml, postup je popísaný v Security_HOWTO.

Keďže LoginModuly nie sú robené ako managed beany, musel som použiť taký malý "hack" na získanie `RedmineUserService` vnútri modulu (je pri ňom komentár).

Na odskúšanie prihlasovania som nastavil url: `http://localhost:8080/tracker/secured` (po úspešnom prihlásení to hodí `404 - Not Found`)

Takže overovanie používateľov máme, treba už len zabezpečiť endpointy pomocou anotácií.

**Comment by vaclavHala** [comment]
Ted pridavam group membership k userum. Kdyz zavolas kteroukoli metodu na soucasnem uzivateli (/me), JSON ktery ti to vrati bude obsahovat seznam skupin kterych je user clenem. Az to bude pridam to zaroven do login modulu misto te natvrdo zadratovane role co je tam ted.

**Comment by vaclavHala** [comment]
Note to self: projit vsechny mozne errory ktere mohou padat a pro kazdy napsat unit test (user api v nekterych pripadech neprezit malformed json - register)

**Comment by ivan-kralik** [comment]
Urobil som používateľské rozhranie pre prihlásenie a registráciu. Mal si pravdu, nakoniec som to urobil tak, že HTTP autentizácia je skrytá používateľovi a riadi si ju angular. Upravil som aj UserResource tak, aby využívalo Java EE Security anotácie a dorobil som tam metódu `login()` na overenie prihlasovacích údajov kvôli prihlasovaniu.

Takže registrácia a prihlasovanie by už mali fungovať - `http://localhost:8080/tracker/index.html`

**Comment by vaclavHala** [comment]
Myslim ze ta metoda login nedava smysl. Urcite je spatne ze je POST protoze nemeni zadny stav na serveru. Ale hlavne dela presne to co /user/me. Proc nejde pouzit primo /user/me? taky vrati OK pokud jsi zadal spravne prihlasovaci udaje a UNAUTHORIZED pokud ne.

**Comment by vaclavHala** [comment]
Btw ten RedmineLoginModule to vubec nepouziva, login() se nikdy nezavola. Do standalone.xml jsem pridal ten security-domain z HOWTO. Jeste neco dalsiho se musi udelat?

**Comment by ivan-kralik** [comment]
Pretože keď pošlem v hlavičke `Authorization` neplatné prihlasovacie údaje, Java EE Security mi vráti 401 a WWW-Authenticate, čo spôsobí, že v prehliadači sa vyhodí prihlasovacie okno používateľovi (aj keď je to XHR). Java EE Security vráti 401 v prípade neplatných prihlasovacích údajov v hlavičke aj vtedy, keď je tam anotácia `@PermitAll`. Proste funguje to, len keď sú v tej hlavičke platné prihlasovacie údaje, alebo nič.

Čo sa týka POST metódy, tak pokiaľ viem, nikde nič nehovorí, že POST metóda _nutne musí_ meniť stav na serveri. Viem len, že GET metóda _nesmie_ meniť stav. Ďalšia vec je, že nie je dobrý nápad posielať prihlasovacie údaje v query stringu, aby sa neocitli niekde v logoch

**Comment by ivan-kralik** [comment]
Aha, zabudol som tam napísať, že ten security-domain treba pridať do uzlu:

`<subsystem xmlns="urn:jboss:domain:security:1.2">` - `<security-domains>`

**Comment by vaclavHala** [comment]
Posilani auth udaju v GET se ale stejne nevyhneme, je to bezstavovy takze do /user/me musis poslat auth vzdycky. O tom ze POST meni stav se mluvi ve specifikaci HTTP protokolu _'The POST method is used to request that the origin server accept the entity enclosed in the request as a new subordinate of the resource identified by the Request-URI in the Request-Line.'_. Basic auth udaje se posilaji v hlavicce, ne v query stringu, hlavicky se myslim v historii dohledat nedaji ale jsity si nejsem.

Na to posilani WWW-Auth se podivam

Jak je to teda s tim security modulem? Nasel jsem ze musi byt deplynuty jako samostatny jar na sever ( http://www.mastertheboss.com/jboss-server/jboss-security/creating-a-custom-jboss-login-module ). Jde to nejak obejit?

**Comment by ivan-kralik** [comment]
Ok, lenže keď sa pozrieš na ľubovoľný web, ktorý má prihlasovanie, tak to je tiež robené cez `POST`. Asi mi na to povieš, že "Ale väčšinou sa na základe toho vytvorí session - takže mení sa stav". Áno, a nemám na to čo povedať. V každom prípade navrhujem, aby sme toto ďalej neriešili. Potom, keď už nebudú horšie alebo dôležitejšie veci na programe, môžeme niečo vymyslieť.

Ja neviem, ja som len pridal tie riadky do toho uzla a fungovalo to (robil som to pomocou toho príkazu, nie manuálnou úpravou súboru). Skús to celé ešte raz vypnúť, zapnúť a deploynúť. Ak nepôjde, skúsime sa spojiť cez videokonferenciu a pozrieme sa na to.

**Comment by vaclavHala** [comment]
Hm porad to nefunguje. Jaky mas Skype prosim?

**Comment by ivan-kralik** [comment]
Moje skype ID som Ti poslal na univerzitný mail. Ale môžeme sa spojiť aj cez ten systém, čo minule.
