### ISSUE TITLE
Map API

### ISSUE THREAD

**Issue by vaclavHala** [vaclavHala/SpatialTracker#2]
Jak budeme resit integraci mapy, overlaye a issues? S mapou jsem sam nikdy nic nedelal ale po rychelm pogoogleni to vypada ze jsou dve zakladni moznosti:
1. customization Google Mapy
   - issues a overlay jsou custom prvky ktere se pridaji primo do mapy pres google api
   - ovladani (posouvani, zoomovani etc.) nechame taky nativni z te mapy
   - js klient z nasich sluzeb natahne issues a overlay a prida je do mapy pro kterou pujde primo na google (nema myslim smysl to hnat pres server protoze se s tim na serveru stejne nic neudela a hrat si na nejaky decoupling - moznost pouzit jinou mapu - nedava v tomhle pripade smysl protoze je vse natvrdo navareno na google ) 
2. samostatne vrstvy
   - kazda z vrstev( mapa, overlay a issues) je samostatna a existuje pro ni jedna sluzba na serveru
   - mapovy podklad je pouzit jako obycejny obrazek z ktereho je ukazan nejaky vyrez (implementace stranou, asi by se to muselo tahat po nejakych dlazdicich)
   - klient ridi ovladani (musi spravne slozit vrstvy na sebe a synchronizovat jejich posouvani / zoom)
   - nejsme tolik zavisli na google API a relane se daji pouzit ruzne mapove podklady

ja bych byl pro prvni moznost protoze je jednoduzsi, zvlast pokud uz nekdo z nas to API umi pouzivat (Ivan?)

**Comment by OndrejPontes** [comment]
Ja som tiež za prvú možnosť

**Comment by ivan-kralik** [comment]
Prvá možnosť plus zadávanie polohy sa zjednoduší:
- google places API na prevod adresy na polohu (súradnice)
- HTML5 geolocation API
