### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by vaclavHala** [vaclavHala/SpatialTracker#3]
Mame mit tri skupiny uzivatelu. Myslim ze jsme se vsichni shodli ze to budou tyhle:
1. Anonymous
   - muze prohlizet vsechny issues
   - do chatu se muze zapojit anonymne
2. Registered
   - muze vlozit a editovat svoje issues
   - muze si nastavit ze chce nejake issue sledovat (melo by jit posolichat s Redminem) 
   - v chatu ma jmeno, ostatni si mohou prohlednout jeho statistiky jako kolik toho nahlasil a tak
3. Worker
   - môže si z existujúcich issues vybrať, na ktorých chce pracovať
   - môže upravovať stav:
     - Nahlásený
   - Akceptovaný/Zamietnutý
   - Vyriešený

Jake udaje chceme o zaregistrovanem uzivateli znat? (nick, password, email, ikonku do chatu? ..)
- nick
- heslo
- e-mail

Kde budeme uzivatele a jejich udaje ukladat:
Redmine podporuje skupiny, to znamena ze muzeme uzivatele i to co jsou za typ ukladat spolu s issues v Redminu. Daji se pouzit custom atributy pro uzivatele stejne jako pro issue. Prakticky by to znamenalo ze vsechno az na overlay je ulozeno v Redminu (pouziva postgres) a v Infinispanu bude overlay, statistiky a tak

**Comment by OndrejPontes** [comment]
Nepáči sa mi to že anonymus si vytvorí issue a potom ho nebude môcť upravovať. Takto nám tam budú vznikať duplicitné issues. Napr.: anonymus vytvorí issue a zadá zlé miesto kde sa daná issue vyskytuje a potom by ju chcel upraviť ale už nebude môcť a tak sa zaregistruje a vytvorí tú istú issue len s iným miestom. 

Vyriešil by som to tak že by som nechal možnosť vytvárať issue len registrovaným uživateľom a registráciu urobil čo najjednoduchšiu.
