### ISSUE TITLE
Issues, Categories, Projects

### ISSUE THREAD

**Issue by vaclavHala** [vaclavHala/SpatialTracker#4]
Jakou strukturu chceme obecne pro issues, co u kazdeho evidujeme? 

Je kazdy issue v nejake kategorii? Existuji nejake predpripravene kategorie?

Je jeden bag do ktereho se sypou vsechny issues, nebo existuji nejake projekty?

Nejake priklady issue ktere budeme evidovat

**Comment by OndrejPontes** [comment]
#### Issue:
- meno
- kategoria
- popis
- foto (volitelne)
- gps suradnice
- ?autor

#### Kategorie:
- pridat
- odobrat
- opravit
- ?staznost

Čo myslíš pod tou treťou otázkou ?

#### Priklady:
- meno: nesvitiaca lampa, kategoria: opravit, popis: ...
- meno: park bez laviciek, kategoria: pridat, popis: ...
- meno: hlucny podnik, kategoria: staznost, popis: ...

**Comment by radike** [comment]
Issue should also have State (Submitted, Approved/Declined, Done), Created date, Address (Street is required).

Catogories: enum in Redmine

No projects.
