### ISSUE TITLE
Apiary

### ISSUE THREAD

**Issue by vaclavHala** [vaclavHala/SpatialTracker#7]
Abyste mohli editovat ten apiary.apib file v online editoru (http://docs.hello165.apiary.io/# k tomu linku se da doklikat i pres odkaz co je v hlavnim README) a updatovat server mock, musim vas k apiary projektu pridat jako team membery. Chce to email na invite, napiste mi sem prosim co tam muzu napsat, nechci davat vas skolni mail do random service nekde na netu..

**Comment by OndrejPontes** [comment]
ondrej.pontes@gmail.com
