### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by OndrejPontes** [vaclavHala/SpatialTracker#8]
Akú štruktúru bude mať ten projekt ? Konkrétne moja časť infinispan, má to byť modul alebo to priamo zakomponujem do už vytvoreného projektu ?

**Comment by vaclavHala** [comment]
Ja bych to nekomplikoval, proste jeden package ve spolecnem waru. Nebo je nejaky dobry duvod to rozdelovat?

**Comment by OndrejPontes** [comment]
ok, len ako si mi to v pondelok popisoval som to pochopil ze to chces ako mensi system ktory budeme integrovat zo zbytkom
